<a href="https://colab.research.google.com/github/Javcm/Intro-a-Deep-Learning-UNAM-FC/blob/main/Tutorial_Pandas_2023_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = "https://www.pythoncentral.io/wp-content/uploads/2021/07/c6h7rok9c2v31.jpg" align = "center" >

<font color = 'blue' size = 8>
Tutorial Pandas

<font size=4>
En este Notebook se aborda el uso de la paqueteria Pandas y su utilidad en diversas aplicaciones.

<font color = 'Black' size = 5>
1.- ¿Por qué Pandas?

<font size=4>

Pandas es un herramienta para manipulación y análisis de datos de código abierto, rápida, poderosa, flexible y fácil de utilizar, construida sobre el lenguaje de programación Python.\
Es de uso común en la ciencia de datos y la inteligencia artificial debido a las ventajas y facilidades que proporciona para cargar, preparar, manipular, modelar y analizar datos.

<font size=4>
Algunas características que hacen útil a Pandas son:

<font size=4>
    
1.- Estructuras de datos similares a matrices ($DataFrame$).\
2.- DataFrames similares a los de otros lenguajes de programación.\
3.- Básicamente, los DataFrames son equivalentes a una tabla.\
4.- Los datos en las columnas deben ser del mismo tipo, pero los datos en renglones pueden variar.\
5.- Altamente flexible para tomar datos de múltiples fuentes.

<font size=4> Cualquier cosa que quieras saber de esta biblioteca en el futuro lo puedes encontrar [aquí](https://pandas.pydata.org/docs/user_guide/index.html)

<font color = 'Black' size = 5>
2.- DataFrames (DF)

<font size=4>
Importamos la paquetería Pandas:

In [2]:
import pandas as pd

<font size=4> Para este ejemplo se utilizó la base de datos **Superconductivty Data Data Set** del repositorio:

[UCI Machine Learning Repository: Superconductivty Data Data Set ](https://archive.ics.uci.edu/ml/datasets/Superconductivty+Data)

<font size=4> 
Hay dos archivos: 

(1) train.csv: contiene 81 características extraídas de 21263 superconductores junto con la temperatura crítica en la columna 82, 


(2) unique_m.csv: contiene la fórmula química dividida para todos los 21263 superconductores del archivo  train.csv 



Las dos últimas columnas tienen la temperatura crítica y la fórmula química. 
    
**El objetivo de este trabajo fue es predecir la temperatura crítica en función de las características extraídas.**

<font size=4> Levantamos el archivo CSV con pandas:

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Classroom/Introducción a Redes Neuronales Temas Selectos de Física Computacional III/Tutorial Pandas/train.csv')

#Mostramos el DataFrame
df

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,29.00
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,2.257143,1.888175,2.210679,1.557113,1.047221,2,1.128571,0.632456,0.468606,26.00
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,19.00
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,22.00
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,2.242857,2.213364,2.206963,1.368922,1.096052,1,1.057143,0.433013,0.428809,23.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21258,4,106.957877,53.095769,82.515384,43.135565,1.177145,1.254119,146.88130,15.504479,65.764081,...,3.555556,3.223710,3.519911,1.377820,0.913658,1,2.168889,0.433013,0.496904,2.44
21259,5,92.266740,49.021367,64.812662,32.867748,1.323287,1.571630,188.38390,7.353333,69.232655,...,2.047619,2.168944,2.038991,1.594167,1.337246,1,0.904762,0.400000,0.212959,122.10
21260,2,99.663190,95.609104,99.433882,95.464320,0.690847,0.530198,13.51362,53.041104,6.756810,...,4.800000,4.472136,4.781762,0.686962,0.450561,1,3.200000,0.500000,0.400000,1.98
21261,2,99.663190,97.095602,99.433882,96.901083,0.690847,0.640883,13.51362,31.115202,6.756810,...,4.690000,4.472136,4.665819,0.686962,0.577601,1,2.210000,0.500000,0.462493,1.84
21262,3,87.468333,86.858500,82.555758,80.458722,1.041270,0.895229,71.75500,43.144000,29.905282,...,4.500000,4.762203,4.242641,1.054920,0.970116,3,1.800000,1.414214,1.500000,12.80

<font size=4> Podemos verificar las dimensiones del DataFrame con el atributo **.shape** como en los arreglos de Python.

In [ ]:
df.shape

(21263, 82)

<font size=4> Observamos que tenemos 21263 superconductores y 82 rasgos (features) de cada uno.

<font size=4> Podemos visualizar los primeros $n$ renglones con el atributo **.head(n)** y los últimos $m$ con **.tail(m)** de la siguiente manera:

In [ ]:
n = 10 
df.head(n)

   number_of_elements  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
0                   4         88.944468  ...         0.437059           29.0
1                   5         92.729214  ...         0.468606           26.0
2                   4         88.944468  ...         0.444697           19.0
3                   4         88.944468  ...         0.440952           22.0
4                   4         88.944468  ...         0.428809           23.0
5                   4         88.944468  ...         0.410326           23.0
6                   4         88.944468  ...         0.349927           11.0
7                   4         76.517718  ...         0.444697           33.0
8                   4         76.517718  ...         0.440952           36.0
9                   4         76.517718  ...         0.437059           31.0

[10 rows x 82 columns]

In [ ]:
m = 5
df.tail(m)

       number_of_elements  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
21258                   4        106.957877  ...         0.496904           2.44
21259                   5         92.266740  ...         0.212959         122.10
21260                   2         99.663190  ...         0.400000           1.98
21261                   2         99.663190  ...         0.462493           1.84
21262                   3         87.468333  ...         1.500000          12.80

[5 rows x 82 columns]

<font size=4> Podemos renombrar una columna en particular utilzando el atributo **.rename()**

In [ ]:
df.rename(columns = {"number_of_elements":"numero_de_elementos"}, inplace = True)  #Cambiamos el nombre de la columna "number_of_elements" 
                                                                                    #por "numero_de_elementos"

       numero_de_elementos  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
0                        4         88.944468  ...         0.437059          29.00
1                        5         92.729214  ...         0.468606          26.00
2                        4         88.944468  ...         0.444697          19.00
3                        4         88.944468  ...         0.440952          22.00
4                        4         88.944468  ...         0.428809          23.00
...                    ...               ...  ...              ...            ...
21258                    4        106.957877  ...         0.496904           2.44
21259                    5         92.266740  ...         0.212959         122.10
21260                    2         99.663190  ...         0.400000           1.98
21261                    2         99.663190  ...         0.462493           1.84
21262                    3         87.468333  ...         1.500000          12.80

[21263 rows x 82 columns]

In [ ]:
df

<font size=4> Podemos acceder a información de las columnas del dataframe mediante el atributo **df.column_name** o mediante la instrucción **df['column_name']**

In [ ]:
#Utilizamos cada uno de los comandos:

df.numero_de_elementos

In [ ]:
df["numero_de_elementos"]

<font size=4> Podemos extraer información de un renglón específico del $DataFrame$  (index) mediante **series** con el atributo **.loc[ ]**:

In [ ]:
df.loc[524]  #Utilizamos el atributo .loc()

numero_de_elementos       4.000000
mean_atomic_mass         96.032850
wtd_mean_atomic_mass     58.347829
gmean_atomic_mass        69.515930
wtd_gmean_atomic_mass    37.476574
                           ...
range_Valence             1.000000
wtd_range_Valence         0.816101
std_Valence               0.433013
wtd_std_Valence           0.269624
critical_temp            85.000000
Name: 524, Length: 82, dtype: float64

<font size=4> Se puede acceder a información en particular utilizando los métodos previos, si por ejemplo queremos obtener la temperatura crítica del superconductor 524:

In [ ]:
df['critical_temp'][524]

<font size=4> En pandas se utilizan también los **operadores de acceso** como el atributo **.iloc[]** que basa su operación en la enumeración de renglones y columnas de Python

<font size=4> Si por ejemplo buscamos la información del superconductor **i-ésimo**, entonces utilizamos **df.iloc[ i ]** el cual obtiene la información del renglón **i-esimo**.

In [ ]:
df.iloc[524]

<font size=4> Si queremos obtener el numero de elementos (columna 0) de todos los superconductores:

In [ ]:
df.iloc[:, 0]

<font size=4> Si queremos obtener el número de elementos y su temperatura crítica de los superconductores 0 y 524:

In [5]:
df.iloc[ [0,524],  [0,81] ]

<font size=4> Como se puede observar, el atributo **.iloc[]** utiliza el índice o posición del superconductor (los renglones en este caso) o las columnas para operar. De distinta manera, **.loc[]** basa su operación en el nombre del índice de los datos, no en su posición o enumeración de Python:

<font size=4> Si queremos obtener el numero de elementos en el superconductor 524:

In [5]:
df.loc[524, 'numero_de_elementos']

<font size=4> Si quieremos obtener el numero de elementos de los superconductores 524 y 342 por ejemplo:

In [ ]:
df.loc[[524, 342], 'numero_de_elementos']

524    4
342    4
Name: numero_de_elementos, dtype: int64

<font size=4> Si quieremos obtener el numero de elementos (columna 0) y temperatura crítica (columna 85) de cada uno de los superconductores:

In [ ]:
df.loc[:, ['numero_de_elementos', "critical_temp"]]

       numero_de_elementos  critical_temp
0                        4          29.00
1                        5          26.00
2                        4          19.00
3                        4          22.00
4                        4          23.00
...                    ...            ...
21258                    4           2.44
21259                    5         122.10
21260                    2           1.98
21261                    2           1.84
21262                    3          12.80

[21263 rows x 2 columns]

<font size=4> Pandas también puede utilizar **operadores lógicos** como **==**, **<** y **>**.

<font size=4> Si queremos obtener los superconductores con temperatura crítica iguala 85 K hacemos lo siguiente:

In [5]:
df.loc[df.critical_temp == 85]

<font size=4> Si queremos obtener los superconductores con temperatura crítica menor a 85 K hacemos lo siguiente:

In [8]:
df.loc[df.critical_temp < 85]

<font size=4> Si queremos los superconductores con temperatura crítica de 83 o de 85 K

In [10]:
df.loc[df.critical_temp.isin( [83, 85] )]

<font size=4> Si queremos identificar todas las posiciones en el dataframe que tienen un valor vacío o **"NaN"**

In [ ]:
#df.loc[df.critical_temp.isnull()].shape
df.loc[df.critical_temp.notnull()].shape

(21263, 82)

<font size=4> Pandas también puede calcular promedios, desviación estándar, etc. y otras funciones útiles, por ejemplo:

<font size=4> El atributo **.describe()** nos da la siguiente información de cada una de las columnas del dataframe:

In [ ]:
df.describe()

       numero_de_elementos  mean_atomic_mass  ...  wtd_std_Valence  critical_temp
count         21263.000000      21263.000000  ...     21263.000000   21263.000000
mean              4.115224         87.557631  ...         0.673987      34.421219
std               1.439295         29.676497  ...         0.455580      34.254362
min               1.000000          6.941000  ...         0.000000       0.000210
25%               3.000000         72.458076  ...         0.306892       5.365000
50%               4.000000         84.922750  ...         0.500000      20.000000
75%               5.000000        100.404410  ...         1.020436      63.000000
max               9.000000        208.980400  ...         3.000000     185.000000

[8 rows x 82 columns]

<font size = 4> Si queremos sólo la información de la temperatura crítica:

In [ ]:
df.critical_temp.describe()

count    21263.000000
mean        34.421219
std         34.254362
min          0.000210
25%          5.365000
50%         20.000000
75%         63.000000
max        185.000000
Name: critical_temp, dtype: float64

<font size=4> El atributo **.mean()** nos regresa el promedio, en este caso, de cada columna:

In [ ]:
#df.critical_temp.mean()

df.mean()

numero_de_elementos       4.115224
mean_atomic_mass         87.557631
wtd_mean_atomic_mass     72.988310
gmean_atomic_mass        71.290627
wtd_gmean_atomic_mass    58.539916
                           ...
range_Valence             2.041010
wtd_range_Valence         1.483007
std_Valence               0.839342
wtd_std_Valence           0.673987
critical_temp            34.421219
Length: 82, dtype: float64

<font color = 'white' size = 5>
3.- Operaciones con DataFrames

<font size=4> El atributo **.unique()** nos regresa los valores posibles que puede tomar un elemento sin repetir:

In [ ]:
df.critical_temp.unique()

array([ 29.   ,  26.   ,  19.   , ...,   1.445,   1.165, 122.1  ])

<font size = 5> Por otro lado, el archivo **unique_m.csv** contiene la composición por elemento de cada uno de los superconductores así como su fórmula.

In [ ]:
df_2 = pd.read_csv('/content/drive/MyDrive/Classroom/Introducción a Deep Learning/Tutorial_Pandas/unique_m.csv')
df_2

         H  He   Li   Be  ...  At  Rn  critical_temp                material
0      0.0   0  0.0  0.0  ...   0   0          29.00         Ba0.2La1.8Cu1O4
1      0.0   0  0.0  0.0  ...   0   0          26.00  Ba0.1La1.9Ag0.1Cu0.9O4
2      0.0   0  0.0  0.0  ...   0   0          19.00         Ba0.1La1.9Cu1O4
3      0.0   0  0.0  0.0  ...   0   0          22.00       Ba0.15La1.85Cu1O4
4      0.0   0  0.0  0.0  ...   0   0          23.00         Ba0.3La1.7Cu1O4
...    ...  ..  ...  ...  ...  ..  ..            ...                     ...
21258  0.0   0  0.0  0.0  ...   0   0           2.44      Tm0.84Lu0.16Fe3Si5
21259  0.0   0  0.0  0.0  ...   0   0         122.10         Tl1Ba2Ca3Cu4O11
21260  0.0   0  0.0  0.0  ...   0   0           1.98              Nb0.8Pd0.2
21261  0.0   0  0.0  0.0  ...   0   0           1.84            Nb0.69Pd0.31
21262  0.0   0  0.0  0.0  ...   0   0          12.80           Fe1Se0.2Te0.8

[21263 rows x 88 columns]

<font size=4> Si queremos agregar a nuestro dataframe original la columna **material** que aparece en este nuevo archivo, hacemos lo siguiente:

In [ ]:
df["compuesto"] = df_2["material"]

In [ ]:
df

       numero_de_elementos  ...               compuesto
0                        4  ...         Ba0.2La1.8Cu1O4
1                        5  ...  Ba0.1La1.9Ag0.1Cu0.9O4
2                        4  ...         Ba0.1La1.9Cu1O4
3                        4  ...       Ba0.15La1.85Cu1O4
4                        4  ...         Ba0.3La1.7Cu1O4
...                    ...  ...                     ...
21258                    4  ...      Tm0.84Lu0.16Fe3Si5
21259                    5  ...         Tl1Ba2Ca3Cu4O11
21260                    2  ...              Nb0.8Pd0.2
21261                    2  ...            Nb0.69Pd0.31
21262                    3  ...           Fe1Se0.2Te0.8

[21263 rows x 83 columns]

<font size=4> Observamos que se agregó la columna **material** ahora con el nombre **compuesto**.

<font color = 'white' size = 5>
4.- Removiendo Null values

<font size=4> Estaremos utilizando el atributo **dataframe.dropna()** cuya documentación puedes consultar [aquí](https://pandas.pydata.org/docs/user_guide/index.html)

<font size=4> Definimos un dataframe de prueba que contenga Null values

In [ ]:
df = pd.DataFrame({
    'colA':[None, False, False, True], 
    'colB': [None, 2, None, 4],
    'colC': [None, 'b', 'c', 'd'],
    'colD': [None, 2.0, 3.0, 4.0],
    })

print(df)

    colA  colB  colC  colD
0   None   NaN  None   NaN
1  False   2.0     b   2.0
2  False   NaN     c   3.0
3   True   4.0     d   4.0

<font size=4> Si quieremos eliminar todos los **renglones** con al menos un valor **NaN** hacemos lo siguiente:

In [ ]:
df_rows = df.dropna()

#Imprimimos el DF
df_rows

    colA  colB colC  colD
1  False   2.0    b   2.0
3   True   4.0    d   4.0

<font size=4> Si quieremos eliminar los **renglones** que **únicamente** tengan valores **NaN** hacemos lo siguiente:

In [ ]:
df_u_rows = df.dropna(how='all')

#Imprimimos el DF
df_u_rows

    colA  colB colC  colD
1  False   2.0    b   2.0
2  False   NaN    c   3.0
3   True   4.0    d   4.0

<font size=4> Si quieremos eliminar los **renglones** que tengan valores **NaN**, **únicamente** en ciertos renglones,  hacemos lo siguiente:

In [ ]:
df_just_some_columns = df.dropna(subset=['colA', 'colC'])

#Imprimimos el DF
df_just_some_columns

    colA  colB colC  colD
1  False   2.0    b   2.0
2  False   NaN    c   3.0
3   True   4.0    d   4.0

<font size=4> En este último caso, definimos en el subconjunto **subset** el nombre de las columnas donde queremos aplicar la eliminación de valores *NaN*.

<font size=4> En algunas ocasiones no queremos eliminar los datos de nuestro dataframe, y en su lugar queremos **reemplazar** los valores **NaN** por 0 u otro valor.

<font size=4> Para este propósito, utilizaremos el atributo **df.fillna()**. Cuya documentación puedes encontrar [aquí](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html).

In [ ]:
df.fillna(0)

    colA  colB colC  colD
0      0   0.0    0   0.0
1  False   2.0    b   2.0
2  False   0.0    c   3.0
3   True   4.0    d   4.0